2019-11-25 10:53:36,722 ERROR: Exception on /explore [GET] [in /home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/wakeforce/microblog/app/routes.py", line 15, in explore
    return render_template('index.html', title = 'Explore', posts = posts)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/wakeforce/microblog/app/templates/index.html", line 10, in template
    {{% for error in form.post.errors %}}
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 583, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/home/wakeforce/microblog/venv/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
